FROM resin/%%RESIN_MACHINE_NAME%%-node:7

WORKDIR /usr/src/app
ENV INITSYSTEM on

COPY package.json ./
RUN JOBS=MAX npm i --unsafe-perm --production && npm cache clean

COPY *.js ./

CMD ["npm", "start"]
